# **********************************************************************
# 
#    Use, duplication, or disclosure by the Government is subject to
# 	     restricted rights as set forth in the DFARS.
#  
# 			   BBN Technologies
# 			    A Division of
# 			   BBN Corporation
# 			  10 Moulton Street
# 			 Cambridge, MA 02138
# 			    (617) 873-3000
#  
# 	  Copyright 1998 by BBN Technologies, A Division of
# 		BBN Corporation, all rights reserved.
#  
# **********************************************************************
# 
# $Source: /cvs/distapps/openmap/Attic/scripts.mk,v $
# $RCSfile: scripts.mk,v $
# $Revision: 1.4 $
# $Date: 1998/07/14 20:05:47 $
# $Author: aculline $
# 
# **********************************************************************


#############
# variables #
#############
SCRIPTS_DIR =	./etc/scripts
SRCDIR =	com/bbn/openmap
PERL =		perl
VERSION_FILE =	./$(SRCDIR)/Environment.java


############
# includes #
############

# get the version information generated by NewVersion.pl
#include jar.mk


#########
# rules #
#########
newversion:
	@echo this target has been deprecated
#		$(PERL) $(SCRIPTS_DIR)/NewVersion.pl $(VERSION_FILE)

majorversion:
	@echo this target has been deprecated
#		$(PERL) $(SCRIPTS_DIR)/NewVersion.pl $(VERSION_FILE) -major

openmap-version.jar:
	@echo this target has been deprecated
#	jar cvf openmap-$(OM_VERSION).jar $(OPENMAP.JAR)
#	jar cvf openmap-$(OM_VERSION).jar $(SRCDIR)/*.class \
#	$(SRCDIR)/*/*.class
