# **********************************************************************
# 
#  BBN Corporation
#  10 Moulton St.
#  Cambridge, MA 02138
#  (617) 873-2000
# 
#  Copyright (C) 1997
#  This software is subject to copyright protection under the laws of 
#  the United States and other countries.
# 
# **********************************************************************
# 
# $Source: /cvs/distapps/openmap/Attic/scripts.mk,v $
# $RCSfile: scripts.mk,v $
# $Revision: 1.1 $
# $Date: 1998/03/16 22:41:45 $
# $Author: tmitchel $
# 
# **********************************************************************


#############
# variables #
#############
SCRIPTS_DIR =	./etc/scripts
SRCDIR =	com/bbn/openmap
PERL =		perl
VERSION_FILE =	./$(SRCDIR)/Environment.java


############
# includes #
############

# get the version information generated by NewVersion.pl
include $(SCRIPTS_DIR)/version
include jar.mk


#########
# rules #
#########
newversion:
		$(PERL) $(SCRIPTS_DIR)/NewVersion.pl $(VERSION_FILE)

majorversion:
		$(PERL) $(SCRIPTS_DIR)/NewVersion.pl $(VERSION_FILE) -major

openmap-version.jar:
	jar cvf0 openmap-$(OM_VERSION).jar $(OPENMAP.JAR)
#	jar cvf0 openmap-$(OM_VERSION).jar $(SRCDIR)/*.class \
#	$(SRCDIR)/*/*.class

openmapz-version.jar:
	jar cvf openmap-$(OM_VERSION).jar $(OPENMAP.JAR)
#	jar cvf openmap-$(OM_VERSION).jar $(SRCDIR)/*.class \
#	$(SRCDIR)/*/*.class
