'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.0.3705.0
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.0.3705.0.
'
Namespace com.bbn.winmap.ProperService
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ProperServiceSoap", [Namespace]:="http://winmap.bbn.com/ImageWebService")>  _
    Public Class ProperService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://winmap.bbn.com/ImageWebService/ProperService.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://winmap.bbn.com/ImageWebService/StartNewImageServer", RequestNamespace:="http://winmap.bbn.com/ImageWebService", ResponseNamespace:="http://winmap.bbn.com/ImageWebService", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function StartNewImageServer() As String
            Dim results() As Object = Me.Invoke("StartNewImageServer", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginStartNewImageServer(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("StartNewImageServer", New Object(-1) {}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndStartNewImageServer(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://winmap.bbn.com/ImageWebService/KillImageServer", RequestNamespace:="http://winmap.bbn.com/ImageWebService", ResponseNamespace:="http://winmap.bbn.com/ImageWebService", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function KillImageServer(ByVal procId As Integer) As String
            Dim results() As Object = Me.Invoke("KillImageServer", New Object() {procId})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginKillImageServer(ByVal procId As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("KillImageServer", New Object() {procId}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndKillImageServer(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://winmap.bbn.com/ImageWebService/KillAllImageServers", RequestNamespace:="http://winmap.bbn.com/ImageWebService", ResponseNamespace:="http://winmap.bbn.com/ImageWebService", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function KillAllImageServers() As String
            Dim results() As Object = Me.Invoke("KillAllImageServers", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginKillAllImageServers(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("KillAllImageServers", New Object(-1) {}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndKillAllImageServers(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://winmap.bbn.com/ImageWebService/GetLayers", RequestNamespace:="http://winmap.bbn.com/ImageWebService", ResponseNamespace:="http://winmap.bbn.com/ImageWebService", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetLayers() As String()
            Dim results() As Object = Me.Invoke("GetLayers", New Object(-1) {})
            Return CType(results(0),String())
        End Function
        
        '<remarks/>
        Public Function BeginGetLayers(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetLayers", New Object(-1) {}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetLayers(ByVal asyncResult As System.IAsyncResult) As String()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String())
        End Function
    End Class
End Namespace
