# **********************************************************************
# 
# <copyright>
# 
#  BBN Technologies, a Verizon Company
#  10 Moulton Street
#  Cambridge, MA 02138
#  (617) 873-8000
# 
#  Copyright (C) BBNT Solutions LLC. All rights reserved.
# 
# </copyright>
# **********************************************************************
# 
# $Source: /cvs/distapps/openmap/src/corba/com/bbn/openmap/util/Attic/Makefile,v $
# $RCSfile: Makefile,v $
# $Revision: 1.1 $
# $Date: 2003/03/14 17:30:30 $
# $Author: dietrick $
# 
# **********************************************************************


default: all

all:
	cd ${OPENMAP_HOME}/src/corba && ${OPENMAP_HOME}/bin/ant -emacs $@.corba

classes:
	cd ${OPENMAP_HOME}/src/corba && ${OPENMAP_HOME}/bin/ant -emacs $@.corba

clean:
	cd ${OPENMAP_HOME}/src/corba && ${OPENMAP_HOME}/bin/ant -emacs $@.corba

distclean:
	cd ${OPENMAP_HOME}/src/corba && ${OPENMAP_HOME}/bin/ant -emacs $@.corba

docs:
	cd ${OPENMAP_HOME}/src/corba && ${OPENMAP_HOME}/bin/ant -emacs $@.corba

clean_docs:
	cd ${OPENMAP_HOME}/src/corba && ${OPENMAP_HOME}/bin/ant -emacs $@.corba

jar:
	cd ${OPENMAP_HOME}/src/corba && ${OPENMAP_HOME}/bin/ant -emacs $@.corba

help:
	cd ${OPENMAP_HOME}/src/corba && ${OPENMAP_HOME}/bin/ant -emacs -projecthelp



