# **********************************************************************
# 
# <copyright>
# 
#  BBN Technologies, a Verizon Company
#  10 Moulton Street
#  Cambridge, MA 02138
#  (617) 873-8000
# 
#  Copyright (C) BBNT Solutions LLC. All rights reserved.
# 
# </copyright>
# **********************************************************************
# 
# $Source: /cvs/distapps/openmap/src/svg/com/bbn/openmap/Attic/Makefile,v $
# $RCSfile: Makefile,v $
# $Revision: 1.1 $
# $Date: 2003/03/14 17:34:08 $
# $Author: dietrick $
# 
# **********************************************************************


default: all

all:
	cd ${OPENMAP_HOME}/src/svg && ${OPENMAP_HOME}/bin/ant -emacs $@.svg

classes:
	cd ${OPENMAP_HOME}/src/svg && ${OPENMAP_HOME}/bin/ant -emacs $@.svg

clean:
	cd ${OPENMAP_HOME}/src/svg && ${OPENMAP_HOME}/bin/ant -emacs $@.svg

distclean:
	cd ${OPENMAP_HOME}/src/svg && ${OPENMAP_HOME}/bin/ant -emacs $@.svg

docs:
	cd ${OPENMAP_HOME}/src/svg && ${OPENMAP_HOME}/bin/ant -emacs $@.svg

clean_docs:
	cd ${OPENMAP_HOME}/src/svg && ${OPENMAP_HOME}/bin/ant -emacs $@.svg

jar:
	cd ${OPENMAP_HOME}/src/svg && ${OPENMAP_HOME}/bin/ant -emacs $@.svg

help:
	cd ${OPENMAP_HOME}/src/svg && ${OPENMAP_HOME}/bin/ant -emacs -projecthelp



