# **********************************************************************
# 
# <copyright>
# 
#  BBN Technologies, a Verizon Company
#  10 Moulton Street
#  Cambridge, MA 02138
#  (617) 873-8000
# 
#  Copyright (C) BBNT Solutions LLC. All rights reserved.
# 
# </copyright>
# **********************************************************************
# 
# $Source: /cvs/distapps/openmap/src/openmap/com/bbn/openmap/tools/icon/Attic/Makefile,v $
# $RCSfile: Makefile,v $
# $Revision: 1.1 $
# $Date: 2003/06/26 17:48:55 $
# $Author: dietrick $
# 
# **********************************************************************


default: classes

all:
	cd ${OPENMAP_HOME}/src/openmap && ${OPENMAP_HOME}/bin/ant -emacs $@.openmap

classes:
	cd ${OPENMAP_HOME}/src/openmap && ${OPENMAP_HOME}/bin/ant -emacs $@.openmap

clean:
	cd ${OPENMAP_HOME}/src/openmap && ${OPENMAP_HOME}/bin/ant -emacs $@.openmap

distclean:
	cd ${OPENMAP_HOME}/src/openmap && ${OPENMAP_HOME}/bin/ant -emacs $@.openmap

docs:
	cd ${OPENMAP_HOME}/src/openmap && ${OPENMAP_HOME}/bin/ant -emacs $@.openmap

clean_docs:
	cd ${OPENMAP_HOME}/src/openmap && ${OPENMAP_HOME}/bin/ant -emacs $@.openmap

jar:
	cd ${OPENMAP_HOME}/src/openmap && ${OPENMAP_HOME}/bin/ant -emacs $@.openmap

help:
	cd ${OPENMAP_HOME}/src/openmap && ${OPENMAP_HOME}/bin/ant -emacs -projecthelp



