# **********************************************************************
# 
# <copyright>
# 
#  BBN Technologies, a Verizon Company
#  10 Moulton Street
#  Cambridge, MA 02138
#  (617) 873-8000
# 
#  Copyright (C) BBNT Solutions LLC. All rights reserved.
# 
# </copyright>
# **********************************************************************
# 
# $Source: /cvs/distapps/openmap/src/j3d/com/bbn/openmap/plugin/pilot/Attic/Makefile,v $
# $RCSfile: Makefile,v $
# $Revision: 1.2 $
# $Date: 2003/03/14 17:27:34 $
# $Author: dietrick $
# 
# **********************************************************************


default: all

all:
	cd ${OPENMAP_HOME}/src/j3d && ${OPENMAP_HOME}/bin/ant -emacs $@.j3d

classes:
	cd ${OPENMAP_HOME}/src/j3d && ${OPENMAP_HOME}/bin/ant -emacs $@.j3d

clean:
	cd ${OPENMAP_HOME}/src/j3d && ${OPENMAP_HOME}/bin/ant -emacs $@.j3d

distclean:
	cd ${OPENMAP_HOME}/src/j3d && ${OPENMAP_HOME}/bin/ant -emacs $@.j3d

docs:
	cd ${OPENMAP_HOME}/src/j3d && ${OPENMAP_HOME}/bin/ant -emacs $@.j3d

clean_docs:
	cd ${OPENMAP_HOME}/src/j3d && ${OPENMAP_HOME}/bin/ant -emacs $@.j3d

jar:
	cd ${OPENMAP_HOME}/src/j3d && ${OPENMAP_HOME}/bin/ant -emacs $@.j3d

help:
	cd ${OPENMAP_HOME}/src/j3d && ${OPENMAP_HOME}/bin/ant -emacs -projecthelp



